% SPDX-License-Identifier: GPL-3.0-or-later
% Copyright (C) 2026 MBESO2D contributors
clear; clc; close all;

repo_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(repo_root, 'src'));
addpath(fullfile(repo_root, 'visualization'));

% Material properties: E and allowable stress are in MPa (N/mm^2).
materials = struct( ...
    'E1', 200000, 'nu1', 0.3, 'sigma_m1', 250, ...
    'E2', 20000,  'nu2', 0.3, 'sigma_m2', 50, ...
    'nu3', 0.3);

nelx = 100;
nely = 60;
structure_width_mm = 1000;
structure_height_mm = 600;
% Explicit unit thickness for the plane-stress model in the internal
% mm-N-MPa unit system.
out_of_plane_thickness_m = 1e-3;  % 1 mm

p = 3.0;       % penalization exponent (passed as options.penal)
tau = 1e-5;    % Compliance convergence tolerance

options = struct( ...
    'materials', materials, ...
    'penal', p, ...
    'tau', tau, ...
    'bc_case', 'cantilever', ...
    'bc_load', 1000, ...
    'verbose', true, ...
    'r1_mm', 20, ...
    'r2_mm', 30, ...
    'even_keep_count', false, ...
    'structure_width', structure_width_mm, ...
    'structure_height', structure_height_mm, ...
    'structure_dimension_unit', 'mm', ...
    'out_of_plane_thickness_m', out_of_plane_thickness_m, ...
    'write_run_report', true);

result = mbeso(nelx, nely, 0.4, 0.01, options);

mbeso_plot_beso_evolution(result);
mbeso_plot_history(result);
mbeso_plot_stress_contours(result);
mbeso_plot_displacement(result);
