clear; clc;

% SPDX-License-Identifier: GPL-3.0-or-later
% Copyright (C) 2026 MBESO2D contributors
close all;
repo_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(repo_root, 'src'));
addpath(fullfile(repo_root, 'visualization'));

% Material properties: E and allowable stress are in MPa (N/mm^2),
% while density is in kg/m^3 as specified by Li and Xie (2021).
materials = struct( ...
    'E1', 200000, 'nu1', 0.3, 'sigma_m1', 250, ...
    'E2', 20000,  'nu2', 0.3, 'sigma_m2', 50, ...
    'nu3', 0.3, ...
    'rho1', 7.8e3, 'rho2', 2.4e3, 'rho0', 0);

nelx = 320;
nely = 80;
structure_width_m = 160;
structure_height_m = 40;
deck_thickness_m = 1.5;

p = 3.0;       % penalization exponent (passed as options.penal)
tau = 1e-3;    % Compliance convergence tolerance
deck_rows = max(1, round(deck_thickness_m / (structure_height_m / nely)));

fixed_solid_mask = false(nely, nelx);
fixed_solid_mask(1:deck_rows, :) = true;

options = struct( ...
    'materials', materials, ...
    'penal', p, ...
    'tau', tau, ...
    'bc_case', 'run_case_3b', ...
    'deck_line_load_N_per_m', 1.0e5, ...
    'deck_load_distribution', 'equal_nodes', ... % 16 MN / 321 nodes = 49,844.23676 N per node.
    'include_self_weight', true, ...
    'gravity', 9.81, ...
    'out_of_plane_thickness_m', 1, ... % Unit out-of-plane width for the 2D plane-stress model.
    'max_iterations', 1000, ...
    'plotting', true, ...
    'verbose', true, ...
    'r1_mm', 750, ...
    'r2_mm', 1500, ...
    'even_keep_count', true, ...
    'structure_width', structure_width_m, ...
    'structure_height', structure_height_m, ...
    'structure_dimension_unit', 'm', ...
    'fixed_solid_mask', fixed_solid_mask, ...
    'write_run_report', true, ...
    'save_result', true);

result = mbeso_fixed_solid(nelx, nely, 0.4, 0.01, options);

mbeso_plot_beso_evolution(result);
mbeso_plot_history(result);
mbeso_plot_stress_contours(result);
mbeso_plot_displacement(result);
