% SPDX-License-Identifier: GPL-3.0-or-later
% Copyright (C) 2026 MBESO2D contributors
function summary = run_regression_checks()
%RUN_REGRESSION_CHECKS Execute and compare the three public examples.

repo_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(repo_root, 'src'));
baseline_file = fullfile(repo_root, 'validation', 'reference_results.csv');
baseline = readtable(baseline_file, 'TextType', 'string');
example_names = ["run_cantilever", "run_case_3a", "run_case_3b"];

rows = cell(numel(example_names), 16);
for k = 1:numel(example_names)
    example_name = example_names(k);
    result = execute_example(example_name);
    reference_row = baseline(strcmp(baseline.example, example_name), :);
    if height(reference_row) ~= 1
        error('Expected one baseline row for %s.', example_name);
    end

    solid_ratio = nnz(result.x > result.settings.xmin) / numel(result.x);
    m1_elements = nnz(result.mi_map == 1);
    m2_elements = nnz(result.mi_map == 2);
    solid_mask = result.x > result.settings.xmin;
    sigma_e = result.response.sigma_e;
    eta = result.response.eta;
    vm_max_full = max(result.response.sigvm(solid_mask));
    tension_eta_full = 100 * max(eta(solid_mask & sigma_e >= 0));
    compression_eta_full = -100 * max(eta(solid_mask & sigma_e < 0));
    relative_compliance_error = abs(result.compliance - reference_row.compliance_N_mm) / ...
        max(abs(reference_row.compliance_N_mm), eps);
    relative_vm_error = relative_error(vm_max_full, reference_row.vm_max_full_MPa);
    relative_tension_eta_error = relative_error( ...
        tension_eta_full, reference_row.tension_eta_full_percent);
    relative_compression_eta_error = relative_error( ...
        compression_eta_full, reference_row.compression_eta_full_percent);
    reference_converged = parse_logical_value(reference_row.converged);
    passed = result.converged == reference_converged && ...
        result.iterations == reference_row.iterations && ...
        abs(solid_ratio - reference_row.solid_ratio) <= eps && ...
        m1_elements == reference_row.m1_elements && ...
        m2_elements == reference_row.m2_elements && ...
        relative_compliance_error <= 1e-8 && ...
        relative_vm_error <= 1e-8 && ...
        relative_tension_eta_error <= 1e-8 && ...
        relative_compression_eta_error <= 1e-8;

    rows(k, :) = {example_name, result.iterations, result.compliance, ...
        solid_ratio, m1_elements, m2_elements, vm_max_full, ...
        tension_eta_full, compression_eta_full, result.converged, ...
        relative_compliance_error, relative_vm_error, ...
        relative_tension_eta_error, relative_compression_eta_error, ...
        passed, result.termination_reason};
end

summary = cell2table(rows, 'VariableNames', { ...
    'example', 'iterations', 'compliance_N_mm', 'solid_ratio', ...
    'm1_elements', 'm2_elements', 'vm_max_full_MPa', ...
    'tension_eta_full_percent', 'compression_eta_full_percent', ...
    'converged', 'relative_compliance_error', 'relative_vm_error', ...
    'relative_tension_eta_error', 'relative_compression_eta_error', ...
    'passed', 'termination_reason'});
disp(summary);
if ~all(summary.passed)
    error('One or more MBESO2D regression checks failed.');
end
fprintf('All MBESO2D regression checks passed.\n');
end

function value = relative_error(actual, reference)
value = abs(actual - reference) / max(abs(reference), eps);
end

function result = execute_example(example_name)
materials = struct( ...
    'E1', 200000, 'nu1', 0.3, 'sigma_m1', 250, ...
    'E2', 20000, 'nu2', 0.3, 'sigma_m2', 50, 'nu3', 0.3);
switch example_name
    case "run_cantilever"
        options = struct( ...
            'materials', materials, 'penal', 3, 'tau', 1e-5, ...
            'bc_case', 'cantilever', 'bc_load', 1000, ...
            'max_iterations', 1000, 'verbose', false, 'plotting', false, ...
            'r1_mm', 20, 'r2_mm', 30, 'even_keep_count', false, ...
            'structure_width', 1000, 'structure_height', 600, ...
            'structure_dimension_unit', 'mm', ...
            'out_of_plane_thickness_m', 1e-3, 'write_run_report', false);
        result = mbeso(100, 60, 0.4, 0.01, options);
    case {"run_case_3a", "run_case_3b"}
        materials.rho1 = 7.8e3;
        materials.rho2 = 2.4e3;
        materials.rho0 = 0;
        nelx = 320;
        nely = 80;
        deck_rows = 3;
        fixed_solid_mask = false(nely, nelx);
        deck_load_node_row = [];
        if example_name == "run_case_3a"
            fixed_solid_mask((nely - deck_rows + 1):nely, :) = true;
            deck_load_node_row = nely - deck_rows + 1;
        else
            fixed_solid_mask(1:deck_rows, :) = true;
        end
        options = struct( ...
            'materials', materials, 'penal', 3, 'tau', 1e-3, ...
            'bc_case', char(example_name), ...
            'deck_line_load_N_per_m', 1e5, ...
            'deck_load_distribution', 'equal_nodes', ...
            'deck_load_node_row', deck_load_node_row, ...
            'include_self_weight', true, 'gravity', 9.81, ...
            'out_of_plane_thickness_m', 1, ...
            'max_iterations', 1000, 'verbose', false, 'plotting', false, ...
            'r1_mm', 750, 'r2_mm', 1500, 'even_keep_count', true, ...
            'structure_width', 160, 'structure_height', 40, ...
            'structure_dimension_unit', 'm', ...
            'fixed_solid_mask', fixed_solid_mask, ...
            'write_run_report', false, 'save_result', false);
        result = mbeso_fixed_solid(nelx, nely, 0.4, 0.01, options);
    otherwise
        error('Unknown example: %s', example_name);
end
end

function value = parse_logical_value(raw_value)
if islogical(raw_value)
    value = raw_value;
    return;
end
text_value = lower(strtrim(string(raw_value)));
if text_value == "true" || text_value == "1"
    value = true;
elseif text_value == "false" || text_value == "0"
    value = false;
else
    error('Unsupported logical value in regression baseline: %s', text_value);
end
end
