% SPDX-License-Identifier: GPL-3.0-or-later
% Copyright (C) 2026 MBESO2D contributors
function summary = run_mesh_independence()
%RUN_MESH_INDEPENDENCE Reproduce the fixed-iteration mesh study.

repo_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(repo_root, 'src'));
addpath(fullfile(repo_root, 'validation'));

mesh_sizes = [50 30; 100 60; 200 120];
iteration_limit = 214;
materials = struct( ...
    'E1', 200000, 'nu1', 0.3, 'sigma_m1', 250, ...
    'E2', 20000, 'nu2', 0.3, 'sigma_m2', 50, 'nu3', 0.3);

rows = cell(size(mesh_sizes, 1), 11);
for k = 1:size(mesh_sizes, 1)
    nelx = mesh_sizes(k, 1);
    nely = mesh_sizes(k, 2);
    options = struct( ...
        'materials', materials, 'penal', 3, 'tau', 1e-3, ...
        'bc_case', 'cantilever', 'bc_load', 1000, ...
        'max_iterations', iteration_limit, 'force_iteration_limit', true, ...
        'verbose', false, 'plotting', false, ...
        'r1_mm', 20, 'r2_mm', 30, 'even_keep_count', false, ...
        'structure_width', 1000, 'structure_height', 600, ...
        'structure_dimension_unit', 'mm', ...
        'out_of_plane_thickness_m', 1e-3, 'write_run_report', false);
    run_timer = tic;
    result = mbeso(nelx, nely, 0.4, 0.01, options);
    runtime_seconds = toc(run_timer);
    metrics40 = compute_excluded_extrema(result, 40);
    m1_fraction = nnz(result.mi_map == 1) / numel(result.mi_map);
    m2_fraction = nnz(result.mi_map == 2) / numel(result.mi_map);
    rows(k, :) = {nelx, nely, result.iterations, result.compliance, runtime_seconds, ...
        m1_fraction, m2_fraction, metrics40.vm_max_full_MPa, ...
        metrics40.vm_max_regular_MPa, metrics40.actual_size_mm, ...
        result.converged};
end

summary = cell2table(rows, 'VariableNames', { ...
    'nelx', 'nely', 'iterations', 'compliance_N_mm', 'runtime_s', ...
    'tension_fraction', 'compression_fraction', 'vm_max_full_MPa', ...
    'vm_max_excluding_40mm_MPa', 'actual_40mm_patch_size_mm', ...
    'converged'});
disp(summary);
end
